# Generated by Django 5.0.4 on 2024-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
                ('email_id', models.EmailField(max_length=254)),
                ('Link', models.URLField()),
            ],
        ),
    ]
