# Generated by Django 5.0.4 on 2024-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_sample_phone_no_alter_sample_link_alter_sample_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
