# Generated by Django 5.0.4 on 2024-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_sample_age1_alter_sample_link_alter_sample_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='age1',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
