# Generated by Django 5.0.4 on 2024-04-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_sample_age_alter_sample_age1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='age1',
            new_name='age2',
        ),
    ]
