# Generated by Django 5.0.4 on 2024-04-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_rename_age1_sample_age2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='age2',
        ),
    ]
