# Generated by Django 5.0.4 on 2024-04-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_remove_sample_age2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
