# Generated by Django 5.0.4 on 2024-04-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='many',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=15)),
                ('emp_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app4.one')),
            ],
        ),
    ]
