# Generated by Django 5.0.4 on 2024-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
